e2e_test_v2
smilemaxdev/RayTracing pull request #4
Opened 2021-10-30 20:56 UTC by ElectroGeorge7

Comparing program output with building triangles.
.ggb files -  triangles in https://www.geogebra.org/3d
.in files - random triangles in 10m3, 100m3, 1000m3, 10000m3 and 100000m3
program_result - the prog output
test_result - manual checking

2021-10-31 15:27 UTC, smilemaxdev requested changes

2021-10-31 15:27 UTC, smilemaxdev commented on tests/test_e2e.hpp
> +    void test_e2e(void){
Зачем здесь (void)?

2021-10-31 15:27 UTC, smilemaxdev commented on tests/test_e2e.hpp
> +        std::fstream randfis1("G:\\validation\\input_rand1.in");
папку внутрь test закинь. Файлы должно быть выидно на любом компе, поэтому сделаем их относительными.

2021-10-31 15:27 UTC, smilemaxdev commented on tests/test_e2e.hpp
> +        randfis1.close();
Зачем их закрывать? Они в деструкторе закрываются.

2021-10-31 15:27 UTC, smilemaxdev commented on tests/test_e2e.hpp
> +    void test_file_e2e(std::fstream& randfis,std::fstream& progfos,std::fstream& testresfos){
Сделай выравнивание табуляцией, чтобы читаемость лучше была и аргументы пиши с пробелами T t, Y y, X x.

2021-10-31 15:27 UTC, smilemaxdev commented on tests/test_e2e.hpp
> +    void testParseTriangles( rytg::BSPtree bsp, std::istream& is){
Здесь сделай передачу дерева по ссылке, а то потенциально здесь UB.

2021-10-31 15:27 UTC, smilemaxdev commented on tests/test_e2e.hpp
> +    void testParseTriangles( rytg::BSPtree bsp, std::istream& is){
Я даже ща специально сделаю ограничение на это внутри дерева.

2021-10-31 15:27 UTC, smilemaxdev commented on tests/test_e2e.hpp
> +    trigArray = test_rytg::parse_input_file(randfis);
Входной файл с треугольниками здесь парсить не надо. Это надо делать только при заполнении дерева.

2021-10-31 15:27 UTC, smilemaxdev commented on tests/test_e2e.hpp
> +    test_rytg::generate_output_file(testresfos, randfis, trigArray);
У нас этот файл должен быть уже готовым, мы не должны его генерировать  каждый раз. Это наш эталонный правильный файл-инвариант с которым мы всегда можем сверится.

2021-10-31 15:27 UTC, smilemaxdev commented on tests/test_e2e.hpp
> +    }
Нигде нет сравнения файла от дерева и эталонного файла, в этом и есть смысл проверки.

2021-11-02 22:35 UTC, ElectroGeorge7 commented on tests/test_e2e.hpp
> +    void test_e2e(void){
Убрал. Не знал, что в С++ можно без void, насколько понял из гугла в С++ void foo() и void foo(void) эквивалентны.

2021-11-02 22:43 UTC, ElectroGeorge7 commented on tests/test_e2e.hpp
> +        randfis1.close();
Убрал. Но не особо понял, в деструкторе дерева или в другом?

2021-11-02 22:46 UTC, ElectroGeorge7 commented on tests/test_e2e.hpp
> +    void test_file_e2e(std::fstream& randfis,std::fstream& progfos,std::fstream& testresfos){
Сделал

2021-11-02 22:52 UTC, ElectroGeorge7 commented on tests/test_e2e.hpp
> +    void testParseTriangles( rytg::BSPtree bsp, std::istream& is){
Сделал. Так нельзя из-за копирования дерева?

2021-11-02 22:59 UTC, ElectroGeorge7 commented on tests/test_e2e.hpp
> +    trigArray = test_rytg::parse_input_file(randfis);
Тут я парсил для функции "тупой" проверки пересечений, чтобы работать с массивом треугольников. Если я правильно понял, то проверка пересечений больше не нужна, результат программы сравнивается с ручной проверкой. Тогда могу убрать ещё generate_output_file()?

2021-11-02 23:02 UTC, ElectroGeorge7 commented on tests/test_e2e.hpp
> +    test_rytg::generate_output_file(testresfos, randfis, trigArray);
Тогда убираю определение функции?

2021-11-02 23:34 UTC, ElectroGeorge7 commented on tests/test_e2e.hpp
> +    test_rytg::generate_output_file(testresfos, randfis, trigArray);
И файлы test_result

2021-11-02 23:36 UTC, ElectroGeorge7 commented on tests/test_e2e.hpp
> +        std::fstream randfis1("G:\\validation\\input_rand1.in");
Сделал

2021-11-03 17:29 UTC, smilemaxdev commented on tests/test_e2e.hpp
> +        randfis1.close();
В деструкторе std::fstream

2021-11-03 21:18 UTC, merged